/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.FrontEnd;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sanu
 */
public class BIll extends javax.swing.JDialog {

    /**
     * Creates new form BIll
     */
    public BIll(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bill();
    }
    
    public void bill()
    {double balance = 0;
    double discount = 0;
    double paycash = 0;
    double cashamount = 0;
             PaymentPortal PaymentPortal1 = new  PaymentPortal(null,true);
             balance = PaymentPortal1.getbalance();
             discount = PaymentPortal1.getdiscount();
             paycash = PaymentPortal1.getpaycash1();
             cashamount = PaymentPortal1.getcashamount();
             
             txt_bill.setText(txt_bill.getText() + "*********************************************************************************************************\n");
             txt_bill.setText(txt_bill.getText() + "                                                                                                                                                                  \n");
             txt_bill.setText(txt_bill.getText() + "                                     Coperative Super Market                                                        \n");
             txt_bill.setText(txt_bill.getText() + "                                                                                                                                                                   \n");
             txt_bill.setText(txt_bill.getText() + "****************************************************************************************************\n");
             
             txt_bill.setText(txt_bill.getText() + "Item No" + "\t\t" + "Item Name"+ "\t\t" +"Price" + "\t\t" + "Qty" + "\t\t" + "Discount" + "\t" + "Total" + "\n");
             
             try{
                 DefaultTableModel dtm = Invoice.dtm;
                
               
                for(int i=0; i< dtm.getRowCount(); i++){
                    
                    String Itemno = (dtm.getValueAt(i, 0).toString());
                    String name = (dtm.getValueAt(i, 1).toString());
                    String price = (dtm.getValueAt(i, 2).toString());
                    String qty = (dtm.getValueAt(i, 3).toString());
                    String dis = (dtm.getValueAt(i, 4).toString());
                    String tot = (dtm.getValueAt(i, 5).toString());
                    
                    txt_bill.setText(txt_bill.getText() + Itemno + "\t\t" + name + "\t\t" + price + "\t\t" + qty + "\t\t" + dis + "\t\t" + tot + "\n");
                    
                }
                txt_bill.setText(txt_bill.getText() + "\n");
                txt_bill.setText(txt_bill.getText() + "\n");
                
                txt_bill.setText(txt_bill.getText() + "\t\t\t" + "\t\t\t\t\t\t" + "Pay Cash    :" + paycash + "\n");
                txt_bill.setText(txt_bill.getText() + "\t\t\t" + "\t\t\t\t\t\t" + "Cash Amount :" + cashamount + "\n");
                txt_bill.setText(txt_bill.getText() + "\t\t\t" + "\t\t\t\t\t\t" + "Discount Amount :" + discount + "\n");
                txt_bill.setText(txt_bill.getText() + "\t\t\t" + "\t\t\t\t\t\t" + "Total Amount :" + balance + "\n");
                
                txt_bill.setText(txt_bill.getText() + "******************************************************************************************************\n");
             txt_bill.setText(txt_bill.getText() + "                                                                                                                                                                   \n");
             txt_bill.setText(txt_bill.getText() + "                                      Thank You Come Again !                                                        \n");
             txt_bill.setText(txt_bill.getText() + "                                                                                                                                                                   \n");
             txt_bill.setText(txt_bill.getText() + "****************************************************************************************************************\n");
             }
             catch(Exception e)
             {
               System.out.println(e.getMessage());
             }
             
             
             
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        btn_credit_cus = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_bill = new javax.swing.JTextArea();
        btn_billprint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_credit_cus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_credit_cus.setText("Credit Customer ");
        btn_credit_cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_credit_cusActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_credit_cus, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 680, 250, 50));

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Invoice Bill");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 255, 70));

        kGradientPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 650, 80));

        panel2.setBackground(new java.awt.Color(0, 0, 0));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_bill.setColumns(20);
        txt_bill.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txt_bill.setRows(5);
        jScrollPane1.setViewportView(txt_bill);

        panel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 820, 510));

        kGradientPanel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 880, 550));

        btn_billprint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_billprint.setText("Print Bill");
        btn_billprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_billprintActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_billprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 680, 220, 50));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_credit_cusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_credit_cusActionPerformed
        CreditCustomerDetails lcd = new CreditCustomerDetails(null,true);
       lcd.setLocationRelativeTo(lcd);
       lcd.setVisible(true);
    }//GEN-LAST:event_btn_credit_cusActionPerformed

    private void btn_billprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_billprintActionPerformed
      try{
        txt_bill.print();
      }
      catch(Exception e)
      {
         System.out.println(e.getMessage());
      }
    }//GEN-LAST:event_btn_billprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BIll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BIll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BIll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BIll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BIll dialog = new BIll(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_billprint;
    private javax.swing.JButton btn_credit_cus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JTextArea txt_bill;
    // End of variables declaration//GEN-END:variables
}
