/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.FrontEnd;

import controller.ManageCahsierLogin;
import controller.ManageCustomerInvoice;
import controller.ManageInvoiceItems;
import controller.ManageItem;
import controller.ManageLoyalityCustomer;
import controller.ManageValidation;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CustomerInvoice;
import model.InvoiceItems;

/**
 *
 * @author Sanu
 */
public class PaymentPortal extends javax.swing.JDialog {

    /**
     * Creates new form PaymentPortal
     */
    public PaymentPortal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setsubtot();
        settotdiscount();
        setnettotal();
    }
        public void setsubtot()
    {
       double finalsubtot = 0;
       Invoice Invoice1 = new Invoice();
       finalsubtot = Invoice1.getsubtot();
       
       txtsubtot.setText(Double.toString(finalsubtot));
    
    }
        
        public void settotdiscount()
        {
            double discount = 0;
         Invoice Invoice1 = new Invoice();
       discount = Invoice1.getdiscount();
       txtdiscount.setText(Double.toString(discount));
       
       
        }
        static double nettotal1 = 0;
        public void setnettotal()
        {
        
              double subtotal =  Double.parseDouble(txtsubtot.getText());
       double discount =  Double.parseDouble(txtdiscount.getText());
       nettotal1 = subtotal - discount;
        txtnettotal.setText(Double.toString(nettotal1));
        txtbalancef.setText(Double.toString(nettotal1));
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtsubtot = new javax.swing.JTextField();
        txtdiscount = new javax.swing.JTextField();
        txtnettotal = new javax.swing.JTextField();
        txtpaycash = new javax.swing.JTextField();
        txtcashamount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtbalancef = new javax.swing.JTextField();
        btngenbill = new javax.swing.JButton();
        btnloyalcus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_detuctpoint = new javax.swing.JButton();
        lbl_diserror = new javax.swing.JLabel();
        lbl_nterror = new javax.swing.JLabel();
        lbl_pcasherror = new javax.swing.JLabel();
        lblpaycasherror = new javax.swing.JLabel();
        lbl_suerror = new javax.swing.JLabel();
        lbl_balerror = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sub Total");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 162, 35));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Discount");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Net Total");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 123, 35));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Pay Cash");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 35));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Credit Amount");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, 35));

        txtsubtot.setEditable(false);
        txtsubtot.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txtsubtot, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 250, -1));

        txtdiscount.setEditable(false);
        txtdiscount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtdiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdiscountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdiscountKeyTyped(evt);
            }
        });
        jPanel1.add(txtdiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 250, -1));

        txtnettotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtnettotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnettotalKeyReleased(evt);
            }
        });
        jPanel1.add(txtnettotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 250, -1));

        txtpaycash.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtpaycash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaycashActionPerformed(evt);
            }
        });
        txtpaycash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpaycashKeyReleased(evt);
            }
        });
        jPanel1.add(txtpaycash, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 250, -1));

        txtcashamount.setEditable(false);
        txtcashamount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtcashamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcashamountKeyReleased(evt);
            }
        });
        jPanel1.add(txtcashamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 250, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("Balance");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        txtbalancef.setEditable(false);
        txtbalancef.setBackground(new java.awt.Color(0, 0, 0));
        txtbalancef.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtbalancef.setForeground(new java.awt.Color(204, 0, 0));
        txtbalancef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbalancefActionPerformed(evt);
            }
        });
        jPanel1.add(txtbalancef, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 250, 63));

        btngenbill.setBackground(new java.awt.Color(0, 0, 0));
        btngenbill.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btngenbill.setForeground(new java.awt.Color(204, 0, 51));
        btngenbill.setText("Generate Bill");
        btngenbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenbillActionPerformed(evt);
            }
        });
        jPanel1.add(btngenbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, 360, 80));

        btnloyalcus.setBackground(new java.awt.Color(204, 255, 255));
        btnloyalcus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnloyalcus.setText("Loyality Customer");
        btnloyalcus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloyalcusActionPerformed(evt);
            }
        });
        jPanel1.add(btnloyalcus, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 270, 60));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("Payment Portal");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        btn_detuctpoint.setBackground(new java.awt.Color(153, 0, 102));
        btn_detuctpoint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_detuctpoint.setText("Deduct Loyality Points");
        btn_detuctpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detuctpointActionPerformed(evt);
            }
        });
        jPanel1.add(btn_detuctpoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 210, 40));

        lbl_diserror.setBackground(new java.awt.Color(255, 0, 0));
        lbl_diserror.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_diserror, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 130, -1));

        lbl_nterror.setBackground(new java.awt.Color(255, 0, 0));
        lbl_nterror.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_nterror, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 130, -1));

        lbl_pcasherror.setBackground(new java.awt.Color(255, 0, 0));
        lbl_pcasherror.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_pcasherror, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 130, -1));

        lblpaycasherror.setBackground(new java.awt.Color(255, 0, 0));
        lblpaycasherror.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblpaycasherror, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 130, -1));

        lbl_suerror.setBackground(new java.awt.Color(255, 0, 0));
        lbl_suerror.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_suerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 130, -1));

        lbl_balerror.setBackground(new java.awt.Color(255, 0, 0));
        lbl_balerror.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lbl_balerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 150, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbalancefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbalancefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbalancefActionPerformed
    
    static double balance1 = 0;
    static double discount1 = 0;
    static double paycash1 = 0;
    static double cashamount1 = 0;
    private void btngenbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenbillActionPerformed
        String memID = null; 
        String InvoiceID = null;
        int pointsone = 0;
        double qty = 0;
        double discount = 0;
        double totdiscount = 0;
        double subtot = 0;
        String time;
        String Date;
        int unit;
        double nettotal = 0;
        double balance = 0;
       
        
        try{
        ManageValidation.validatorText(txtsubtot, lbl_suerror);
            ManageValidation.validatorText(txtdiscount, lbl_diserror);
            ManageValidation.validatorText(txtnettotal, lbl_nterror);
            ManageValidation.validatorText(txtpaycash, lbl_pcasherror);
            ManageValidation.validatorText(txtpaycash, lbl_pcasherror);
            ManageValidation.validatorText(txtcashamount, lblpaycasherror);
            ManageValidation.validatorText(txtbalancef, lbl_balerror);
            
            if(ManageValidation.validatorText(txtsubtot, lbl_suerror)
                    &&ManageValidation.validatorText(txtdiscount, lbl_diserror)
                    &&ManageValidation.validatorText(txtnettotal, lbl_nterror)
                    &&ManageValidation.validatorText(txtpaycash, lbl_pcasherror)
                    &&ManageValidation.validatorText(txtpaycash, lbl_pcasherror)
                    &&ManageValidation.validatorText(txtcashamount, lblpaycasherror)
                    &&ManageValidation.validatorText(txtbalancef, lbl_balerror))
                    
            {
                if(Double.parseDouble(txtpaycash.getText()) >= Double.parseDouble(txtnettotal.getText()))
                {
                    LoyalitycardDetails lcd = new LoyalitycardDetails(null,true);
                    memID = lcd.getMemID();
                    pointsone = lcd.getpointsone();
                    //
                    Invoice Invoice1 = new Invoice();
                    InvoiceID = Invoice1.getIvoiceID();
                    qty = Invoice1.getqty();
                    totdiscount = Double.parseDouble(txtdiscount.getText());
                    time = Invoice1.gettime();
                    Date = Invoice1.getdate();
                    unit = Invoice1.getunit();
                    
                    nettotal = Double.parseDouble(txtnettotal.getText());
                    //
                    
                    discount = Double.parseDouble(txtdiscount.getText());
                    //
                    subtot = Double.parseDouble(txtsubtot.getText());
                    //
                    balance = Double.parseDouble(txtbalancef.getText());
                   
                    //
                    UserSignin user = new UserSignin(null,true);
            
                   //geting shift number
                   ResultSet result = null;
                   String shiftNo = "";
                   ManageCahsierLogin ManageCahsierLogin1 = new ManageCahsierLogin();
                   result = ManageCahsierLogin1.getcashierlogin();
                   while(result.next())
                   {
                     shiftNo = result.getString("shiftNo").toString();
                   }
                    
                    
                CustomerInvoice c1 = new CustomerInvoice(memID,InvoiceID,pointsone,qty,totdiscount,subtot,Date,time,unit,nettotal,balance,Double.parseDouble(txtcashamount.getText()),Double.parseDouble(txtpaycash.getText()),1,shiftNo);
                ManageCustomerInvoice m1 = new ManageCustomerInvoice(c1);
                m1.saveInvoice();
                
                DefaultTableModel dtm = Invoice.dtm;
                
                int row = dtm.getRowCount();
                for(int i=0; i< row; i++){
                    System.out.println(dtm.getValueAt(i, 1));
                    System.out.println(dtm.getValueAt(i, 2));
                    System.out.println(dtm.getValueAt(i, 3));
                    System.out.println(dtm.getValueAt(i, 4));
                    
                    InvoiceItems InvoiceItems1 = new InvoiceItems(Integer.parseInt(dtm.getValueAt(i, 0).toString()),InvoiceID,Double.parseDouble(dtm.getValueAt(i, 3).toString()),Double.parseDouble(dtm.getValueAt(i, 2).toString()),Double.parseDouble(dtm.getValueAt(i, 4).toString()),Double.parseDouble(dtm.getValueAt(i, 5).toString()));
                    ManageInvoiceItems ManageInvoiceItems1 = new ManageInvoiceItems(InvoiceItems1);
                    ManageInvoiceItems1.saveInvoiceItems();
double sQty=0, mQty=0;
                                ManageItem item  = new ManageItem();
                                ResultSet re = item.getItemStock(Integer.valueOf(dtm.getValueAt(i, 0).toString()));

                                while(re.next()){   
                                    sQty = re.getDouble("stockQty");
                                    mQty = re.getDouble("maxQty");
                                }

                                sQty = sQty - Double.valueOf(dtm.getValueAt(i, 3).toString());
                                int t = item.UpdateItemStock(Integer.valueOf(dtm.getValueAt(i, 0).toString()), sQty);
//
//                                if(t==1){
//                                    ++c;
//                                }else{
//                                    JOptionPane.showMessageDialog(null, "Error in updating disposal item no " + dtm.getValueAt(index, 1).toString(), "SuperMarket Management", JOptionPane.ERROR_MESSAGE);
//                                }    
                    
                }
                
                txtsubtot.setText("");
//                txtdiscount.setText("");
                txtnettotal.setText("");
//                txtpaycash.setText("");
//                txtcashamount.setText("");
//                txtbalancef.setText("");
              discount1 = Double.parseDouble(txtdiscount.getText());;
          paycash1 = Double.parseDouble(txtpaycash.getText());;
          cashamount1 = Double.parseDouble(txtcashamount.getText());
          balance1 = Double.parseDouble(txtbalancef.getText());
          BIll b1 = new BIll(null,true);
          b1.setLocationRelativeTo(this);
          b1.setVisible(true);
          this.dispose();
                }
                else
                {
                  JOptionPane.showMessageDialog(null, "Pay Cash Amount should be Greater than net Amount","Super MArket Pos System",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        catch(Exception e)
        {
          System.out.println("generate invoice " +e.getMessage());
        }
    }//GEN-LAST:event_btngenbillActionPerformed

    public void setBalnce()
    {
       
    }
             public double getcashamount()
    {
       return cashamount1;
    }
            public double getpaycash1()
    {
       return paycash1;
    }
        public double getdiscount()
    {
       return discount1;
    }
    public double getbalance()
    {
       return balance1;
    }
    private void btnloyalcusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloyalcusActionPerformed
                   ManageValidation.validatorText(txtsubtot, lbl_suerror);
            ManageValidation.validatorText(txtdiscount, lbl_diserror);
            ManageValidation.validatorText(txtnettotal, lbl_nterror);
            ManageValidation.validatorText(txtpaycash, lbl_pcasherror);
            ManageValidation.validatorText(txtpaycash, lbl_pcasherror);
            ManageValidation.validatorText(txtcashamount, lblpaycasherror);
            ManageValidation.validatorText(txtbalancef, lbl_balerror);
            
            if(ManageValidation.validatorText(txtsubtot, lbl_suerror)
                    &&ManageValidation.validatorText(txtdiscount, lbl_diserror)
                    &&ManageValidation.validatorText(txtnettotal, lbl_nterror)
                    &&ManageValidation.validatorText(txtpaycash, lbl_pcasherror)
                    &&ManageValidation.validatorText(txtpaycash, lbl_pcasherror)
                    &&ManageValidation.validatorText(txtcashamount, lblpaycasherror)
                    &&ManageValidation.validatorText(txtbalancef, lbl_balerror))
            {
        LoyalitycardDetails lcd = new LoyalitycardDetails(null,true);
       lcd.setLocationRelativeTo(lcd);
       lcd.setVisible(true);
            }
       
    }//GEN-LAST:event_btnloyalcusActionPerformed

    private void txtdiscountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiscountKeyTyped
   
    }//GEN-LAST:event_txtdiscountKeyTyped
    
    private void txtdiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiscountKeyReleased
        ManageValidation.validateNumber(txtdiscount, 7);     
    }//GEN-LAST:event_txtdiscountKeyReleased

    private void txtpaycashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpaycashKeyReleased
         ManageValidation.validateNumber(txtpaycash, 7); 
        double nettotal = Double.parseDouble(txtnettotal.getText());
         double paycash  = Double.parseDouble(txtpaycash.getText());
         double creditamount = paycash - nettotal;
         txtcashamount.setText(Double.toString(creditamount));
         
    }//GEN-LAST:event_txtpaycashKeyReleased
    
    public double getpaycash()
    {
     
      System.out.print(nettotal1);
      return nettotal1;
    }
    
    private void txtpaycashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaycashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpaycashActionPerformed

    private void btn_detuctpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detuctpointActionPerformed
        String memId = null;
        double totbal = 0;
        double points = 0;
        double bal = 0;
        try{
            ManageValidation.validatorText(txtsubtot, lbl_suerror);
            ManageValidation.validatorText(txtdiscount, lbl_diserror);
            ManageValidation.validatorText(txtnettotal, lbl_nterror);
            ManageValidation.validatorText(txtpaycash, lbl_pcasherror);
            ManageValidation.validatorText(txtpaycash, lbl_pcasherror);
            ManageValidation.validatorText(txtcashamount, lblpaycasherror);
            ManageValidation.validatorText(txtbalancef, lbl_balerror);
            
            if(ManageValidation.validatorText(txtsubtot, lbl_suerror)
                    &&ManageValidation.validatorText(txtdiscount, lbl_diserror)
                    &&ManageValidation.validatorText(txtnettotal, lbl_nterror)
                    &&ManageValidation.validatorText(txtpaycash, lbl_pcasherror)
                    &&ManageValidation.validatorText(txtpaycash, lbl_pcasherror)
                    &&ManageValidation.validatorText(txtcashamount, lblpaycasherror)
                    &&ManageValidation.validatorText(txtbalancef, lbl_balerror))
            {
        LoyalitycardDetails lcd = new LoyalitycardDetails(null,true);
        memId = lcd.getMemID();
        points = lcd.gettotpoint();
        if(memId != null)
        {
            
            bal = Double.parseDouble(txtbalancef.getText());
            if(bal >= points)
            {
            totbal = bal - points;
            points = 0;
            txtbalancef.setText(Double.toString(totbal));
            
            ManageLoyalityCustomer mlC = new ManageLoyalityCustomer();
            mlC.updateloyalitycustomer(memId, points);
            }
            else
            {
               totbal = bal - bal+10;
               points = points - bal+10;
               txtbalancef.setText(Double.toString(totbal));
               ManageLoyalityCustomer m2C = new ManageLoyalityCustomer();
               m2C.updateloyalitycustomer(memId, points);
            }
          
        }
        else
        {
          JOptionPane.showMessageDialog(null, "Please Enter Loyality card details First", "Super Market Pos System", JOptionPane.ERROR_MESSAGE);
        }
            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_btn_detuctpointActionPerformed

    private void txtnettotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnettotalKeyReleased
       ManageValidation.validateNumber(txtnettotal, 7); 
    }//GEN-LAST:event_txtnettotalKeyReleased

    private void txtcashamountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcashamountKeyReleased
       ManageValidation.validateNumber(txtcashamount, 7); 
    }//GEN-LAST:event_txtcashamountKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PaymentPortal dialog = new PaymentPortal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_detuctpoint;
    private javax.swing.JButton btngenbill;
    private javax.swing.JButton btnloyalcus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_balerror;
    private javax.swing.JLabel lbl_diserror;
    private javax.swing.JLabel lbl_nterror;
    private javax.swing.JLabel lbl_pcasherror;
    private javax.swing.JLabel lbl_suerror;
    private javax.swing.JLabel lblpaycasherror;
    private javax.swing.JTextField txtbalancef;
    private javax.swing.JTextField txtcashamount;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txtnettotal;
    private javax.swing.JTextField txtpaycash;
    private javax.swing.JTextField txtsubtot;
    // End of variables declaration//GEN-END:variables
}
