/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.FrontEnd;

import controller.ManageCahsierLogin;
import controller.ManageFrontLogin;
import controller.ManageUser;
import controller.ManageValidation;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import model.frontlogin;
import model.CashierLogin;

/**
 *
 * @author Sanu
 */
public class UserSignin extends javax.swing.JDialog {

    /**
     * Creates new form UserSignin
     */
    public UserSignin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        datetime.datePicker.setDateToToday();
        datetime.timePicker.setTimeToNow();
        generateID();
        generateusername();
        
        
        
    }
    
    public void generateID()
    {
        try{
        ResultSet rs = null;
         String ShiftID = "";
        ManageCahsierLogin c1 = new ManageCahsierLogin();
       rs =  c1.getcashierlogin();
       while(rs.next())
       {
           ShiftID = rs.getString("shiftNo").toString();
       }
       
       if(ShiftID == ""){
                ShiftID = "DSN21DM000001";
            }else{
                int no = Integer.valueOf(ShiftID.substring(8));
                int nno = ++no;
            
                if(String.valueOf(nno).length() == 1){
                    ShiftID = "DSN21DM00000" + String.valueOf(nno);
                }else if(String.valueOf(nno).length() == 2){
                    ShiftID = "DSN21DM0000" + String.valueOf(nno);
                }else if(String.valueOf(nno).length() == 3){
                    ShiftID = "DSN21DM000" + String.valueOf(nno);
                }else if(String.valueOf(nno).length() == 4){
                    ShiftID = "DSN21DM00" + String.valueOf(nno);
                }else if(String.valueOf(nno).length() == 5){
                    ShiftID = "DSN21DM0" + String.valueOf(nno);
                }else{
                    ShiftID = "DSN21DM" + String.valueOf(nno);
                }
            } 
       lbl_snumber.setText(ShiftID);
       
        }
        catch(Exception e)
        {
          System.out.println(e.getMessage());
        }
         
    
    }
    
    public void generateusername()
    {
        frontlogin flog1 = new frontlogin();
        lbl_uname.setText(flog1.getuserId());
        
    /*    try {
            ResultSet rst = null;
            String username =
            ManageCahsierLogin Managecashier1 = new ManageCahsierLogin();
            rst = Managecashier1.getcashierlogin();
            while (rst.next()) 
            {
               rst.getString("Uname").toString();
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pwd_password = new javax.swing.JPasswordField();
        txt_counter = new javax.swing.JTextField();
        txt_floatamount = new javax.swing.JTextField();
        btn_signon = new javax.swing.JButton();
        datetime = new com.github.lgooddatepicker.components.DateTimePicker();
        lbl_snumber = new javax.swing.JLabel();
        lbl_uname = new javax.swing.JLabel();
        lbl_famouterror = new javax.swing.JLabel();
        lbl_countererror = new javax.swing.JLabel();
        lbl_pwderror1 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("User Sign On");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        kGradientPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 380, 60));

        jPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 940, 90));

        jLabel2.setText("User Name");
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 145, 41));

        jLabel3.setText("Password");
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jLabel4.setText("Counter");
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        jLabel5.setText("Float Amount");
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, -1));

        jLabel6.setText("Shift Number");
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel7.setText("Date");
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, -1));

        jLabel8.setText("Time");
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, -1, -1));
        jPanel1.add(pwd_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 210, 40));

        txt_counter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_counterActionPerformed(evt);
            }
        });
        txt_counter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_counterKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_counterKeyReleased(evt);
            }
        });
        jPanel1.add(txt_counter, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 210, 40));

        txt_floatamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_floatamountKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_floatamountKeyReleased(evt);
            }
        });
        jPanel1.add(txt_floatamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 210, 40));

        btn_signon.setText("Sign On");
        btn_signon.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_signon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signonActionPerformed(evt);
            }
        });
        jPanel1.add(btn_signon, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 290, 50));
        jPanel1.add(datetime, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        lbl_snumber.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_snumber.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(lbl_snumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 230, 30));

        lbl_uname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(lbl_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 210, 40));

        lbl_famouterror.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lbl_famouterror, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, 150, 20));

        lbl_countererror.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lbl_countererror, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 150, 20));

        lbl_pwderror1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lbl_pwderror1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 150, 20));

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 640));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_signonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signonActionPerformed
     
     /*   try{
        frontlogin flogin1 = new frontlogin();
        String password = "";
      System.out.println("error check" +pwd_password.getText());
     ResultSet rs = null;
     ManageUser mu1 = new ManageUser();
     rs = mu1.loadUserSearch("C001");
            while (rs.next()) {
             password =   rs.getString("Password");
            }
            System.out.println("error check2" +password);
       
    if("sandun123#" != "sandun123#")
    {
            JOptionPane.showMessageDialog(null, "Password is correct");
    }
    else
    {
       JOptionPane.showMessageDialog(null, "Password is incorrect");
    }
        }
         catch(Exception e)
        {
          System.out.println(e.getMessage());
        } */
     
             try{
                 //use  here because i want to get error message for all the empty text fields
                 ManageValidation.validatorText(pwd_password, lbl_pwderror1);
                         ManageValidation.validatorText(txt_counter, lbl_countererror);
                         ManageValidation.validatorText(txt_floatamount, lbl_famouterror);
                         
                         
                 if(ManageValidation.validatorText(pwd_password, lbl_pwderror1)
                         &&ManageValidation.validatorText(txt_counter, lbl_countererror)
                         &&ManageValidation.validatorText(txt_floatamount, lbl_famouterror)
                         )
                 {
                 frontlogin flogin1 = new frontlogin();
        frontlogin login = new frontlogin(flogin1.getuserId(),pwd_password.getText());
         ManageFrontLogin mlogin = new ManageFrontLogin(login);
         ResultSet rs = mlogin.loadlogin();
         if(rs.next())
         {
             CashierLogin cashierlogin1 = new CashierLogin(lbl_snumber.getText(),lbl_uname.getText(),Integer.parseInt(txt_counter.getText()),datetime.datePicker.getDate().toString(),datetime.timePicker.getTime().toString(),Double.parseDouble(txt_floatamount.getText()),"",""); 
               ManageCahsierLogin manageclog = new ManageCahsierLogin(cashierlogin1);
               int result = manageclog.saveCashierlogin();
               if(result > 0)
               {
                    FrontDashboard Frontdb1 = new FrontDashboard();
                     this.dispose();
                    Frontdb1.setLocationRelativeTo(this);
                     Frontdb1.setVisible(true);
               }
               else
               {
                 JOptionPane.showMessageDialog(null, "Cannot Sign please check Again", "Super Market Pos",JOptionPane.ERROR_MESSAGE);
               }
         }
         else{
                JOptionPane.showMessageDialog(null, "User Name and Password not matched");
              
                pwd_password.setText("");
         }
        }
             }
        catch(Exception e)
        {
          System.out.println("error1" +e.getMessage());
        }
             
      
    }//GEN-LAST:event_btn_signonActionPerformed

    private void txt_floatamountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_floatamountKeyPressed
       
    }//GEN-LAST:event_txt_floatamountKeyPressed

    private void txt_counterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_counterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_counterActionPerformed

    private void txt_counterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_counterKeyPressed
       
    }//GEN-LAST:event_txt_counterKeyPressed

    private void txt_counterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_counterKeyReleased
         ManageValidation.validateNumber(txt_counter, 4);
    }//GEN-LAST:event_txt_counterKeyReleased

    private void txt_floatamountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_floatamountKeyReleased
         ManageValidation.validateNumber(txt_floatamount, 10);
    }//GEN-LAST:event_txt_floatamountKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserSignin dialog = new UserSignin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_signon;
    private com.github.lgooddatepicker.components.DateTimePicker datetime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lbl_countererror;
    private javax.swing.JLabel lbl_famouterror;
    private javax.swing.JLabel lbl_pwderror1;
    private javax.swing.JLabel lbl_snumber;
    private javax.swing.JLabel lbl_uname;
    private javax.swing.JPasswordField pwd_password;
    private javax.swing.JTextField txt_counter;
    private javax.swing.JTextField txt_floatamount;
    // End of variables declaration//GEN-END:variables
}
