/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.BasicInformation;

import controller.ManageCreditInformation;
import controller.ManageDepartment;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sanu
 */
public class Credit_Type_Info_search extends javax.swing.JDialog {

    /**
     * Creates new form Credit_Type_Info_search
     */
    public Credit_Type_Info_search(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try{
        loadcredittype();
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtdepartmentsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcredittype = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 255, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 102, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Search Credit Type  name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, 30));

        txtdepartmentsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdepartmentsearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdepartmentsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtdepartmentsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 200, 30));

        tblcredittype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblcredittype.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Credit Type Code", "Credit Type Name"
            }
        ));
        tblcredittype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcredittypeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcredittype);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 510, 270));

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 530, 360));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 560, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdepartmentsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdepartmentsearchKeyPressed

    }//GEN-LAST:event_txtdepartmentsearchKeyPressed

    public void loadcredittype() throws Exception
    {
        ResultSet result = null;
        ManageCreditInformation ctm = new ManageCreditInformation();
        result = ctm.loadCreditCustomerType();
        DefaultTableModel model = (DefaultTableModel) tblcredittype.getModel();
        while(result.next())
        {
           Vector vec = new Vector();
           vec.add(result.getInt("ccode"));
           vec.add(result.getString("TypeName"));
           
           model.addRow(vec);
           
        
        }
        
        tblcredittype.setModel(model);
    
    }
    private void txtdepartmentsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdepartmentsearchKeyReleased

    }//GEN-LAST:event_txtdepartmentsearchKeyReleased

    public String ccode = "";
    public String cname = "";
    private void tblcredittypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcredittypeMouseClicked
        DefaultTableModel DtM = (DefaultTableModel)tblcredittype.getModel();
        int selectedrowindex = tblcredittype.getSelectedRow();
        ccode =  (DtM.getValueAt(selectedrowindex , 0).toString());
        cname =  (DtM.getValueAt(selectedrowindex , 1).toString());

        this.dispose();
    
    }//GEN-LAST:event_tblcredittypeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credit_Type_Info_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credit_Type_Info_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credit_Type_Info_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credit_Type_Info_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Credit_Type_Info_search dialog = new Credit_Type_Info_search(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTable tblcredittype;
    private javax.swing.JTextField txtdepartmentsearch;
    // End of variables declaration//GEN-END:variables
}
