/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.FontFormatException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Sanu
 */
public class Dashboard1 extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard1
     */
    public Dashboard1() {
            
        initComponents();
        
        runLetters();
        Menu Menu1 = new Menu();
              jmenupanel.removeAll();
              jmenupanel.add(Menu1).setVisible(true);
    }

    
        void runLetters(){
        Thread t = new Thread(){
            @Override
            public void run(){
            String names[] = {"C" , "O" , "-" , "O" , "P" , "E" , "R" , "A" , "T" , "I" , "V" , "E " , "  " , "P" , "O" , "S" , "  ","S" , "Y" , "S" , "T" , "E" , "M" ,  };
            while(true){ 
            String title = "";
            for(int i =0; i < names.length ; i++){
            title = title +names[i];
            try{
             jLabel8.setText(title);
             Thread.sleep(300);
            }
            catch(Exception e){
                
            }
            }
            }
            }
            
        };
        t.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        btn_menu = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        btn_basicinformsation = new javax.swing.JButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jmenupanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 51));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(102, 102, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 0, 51));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_menu.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        btn_menu.setText("මෙනුව");
        btn_menu.setToolTipText("");
        btn_menu.setActionCommand("btn1");
        btn_menu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51)));
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, 90));

        jButton2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton2.setText("සටහන් ඇතුලත් කිරීම");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 350, 90));

        jButton3.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton3.setText("වාර්තා තොරතුරු");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 350, 90));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 370, 110));

        jButton4.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton4.setText("උදව්");
        kGradientPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 350, 90));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 370, 110));

        jButton5.setFont(new java.awt.Font("Nirmala UI", 1, 22)); // NOI18N
        jButton5.setText("පරිශීලක කළමණාකරණය");
        kGradientPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 350, 90));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 370, 110));

        jButton6.setFont(new java.awt.Font("Nirmala UI", 1, 22)); // NOI18N
        jButton6.setText("ඉවත්වීම");
        kGradientPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 350, 90));

        btn_basicinformsation.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        btn_basicinformsation.setText("මූලික තොරතුරු");
        btn_basicinformsation.setToolTipText("");
        btn_basicinformsation.setActionCommand("btn1");
        btn_basicinformsation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_basicinformsationActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btn_basicinformsation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 350, 90));

        jDesktopPane1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 390, 800));

        kGradientPanel2.setBackground(new java.awt.Color(255, 204, 204));
        kGradientPanel2.setForeground(new java.awt.Color(255, 153, 102));
        kGradientPanel2.setkEndColor(new java.awt.Color(0, 51, 51));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 0, 0));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("System Back End ");
        kGradientPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 240, 30));

        jDesktopPane1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 390, 50));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 870, 70));

        javax.swing.GroupLayout jmenupanelLayout = new javax.swing.GroupLayout(jmenupanel);
        jmenupanel.setLayout(jmenupanelLayout);
        jmenupanelLayout.setHorizontalGroup(
            jmenupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1490, Short.MAX_VALUE)
        );
        jmenupanelLayout.setVerticalGroup(
            jmenupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );

        jDesktopPane1.add(jmenupanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 1490, 860));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_basicinformsationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_basicinformsationActionPerformed
             
        try {
            BasicInfo bi = new BasicInfo();
            jmenupanel.removeAll();
            jmenupanel.add(bi).setVisible(true); 
              
        } catch (FontFormatException ex) {
            Logger.getLogger(Dashboard1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Dashboard1.class.getName()).log(Level.SEVERE, null, ex);
        }
             
              
              
    }//GEN-LAST:event_btn_basicinformsationActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
              Menu Menu1 = new Menu();
              jmenupanel.removeAll();
              jmenupanel.add(Menu1).setVisible(true);
    }//GEN-LAST:event_btn_menuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
              Entry__Note bi = null;
        try {
            bi = new Entry__Note();
        } catch (FontFormatException ex) {
            Logger.getLogger(Dashboard1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Dashboard1.class.getName()).log(Level.SEVERE, null, ex);
        }
            jmenupanel.removeAll();
            jmenupanel.add(bi).setVisible(true); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ReportsForm RF = new ReportsForm();
       jmenupanel.removeAll();
        jmenupanel.add(RF).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_basicinformsation;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jmenupanel;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
