/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import view.Report.DailyGRNsummaryreport;
import view.Report.DailyInvoiceDetailsReport;
import view.Report.DailyInvoiceItemSalesReport;
import view.Report.DailyInvoiceSummaryReport;
import view.Report.DailyWastageReport;
import view.Report.Daily_Invoice_Credit_Sales;
import view.Report.dailyitemchangeviewreport;

/**
 *
 * @author Sanu
 */
public class ReportsForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReportsForm
     */
    public ReportsForm() {
        initComponents();
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_pricechangereport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnrackdetails = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnitemdetails1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnsupplierdetails1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnsubloc1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btncategorydetails = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnItemAlertBin = new javax.swing.JButton();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        lbldepartmentdet = new javax.swing.JLabel();
        lbldepartmentcount = new javax.swing.JLabel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        kGradientPanel8 = new keeptoo.KGradientPanel();
        kGradientPanel9 = new keeptoo.KGradientPanel();
        kGradientPanel10 = new keeptoo.KGradientPanel();
        kGradientPanel11 = new keeptoo.KGradientPanel();
        kGradientPanel12 = new keeptoo.KGradientPanel();
        lblrack = new javax.swing.JLabel();
        lblRackcount = new javax.swing.JLabel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        lblsupplier = new javax.swing.JLabel();
        lblsupplierscount = new javax.swing.JLabel();
        kGradientPanel13 = new keeptoo.KGradientPanel();
        kGradientPanel14 = new keeptoo.KGradientPanel();
        kGradientPanel15 = new keeptoo.KGradientPanel();
        kGradientPanel16 = new keeptoo.KGradientPanel();
        kGradientPanel17 = new keeptoo.KGradientPanel();
        kGradientPanel18 = new keeptoo.KGradientPanel();
        kGradientPanel19 = new keeptoo.KGradientPanel();
        kGradientPanel20 = new keeptoo.KGradientPanel();
        lblItem = new javax.swing.JLabel();
        lblItemCount = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setBackground(new java.awt.Color(51, 51, 51));
        kGradientPanel1.setkEndColor(new java.awt.Color(153, 153, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(51, 0, 51));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_pricechangereport.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_pricechangereport.setText("Daily Item Price Change Report");
        btn_pricechangereport.setBorder(null);
        btn_pricechangereport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pricechangereportActionPerformed(evt);
            }
        });
        jPanel1.add(btn_pricechangereport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 50));

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 400, 70));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnrackdetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnrackdetails.setText("Daily Invoice Summary Report");
        btnrackdetails.setBorder(null);
        btnrackdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrackdetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnrackdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 50));

        kGradientPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 400, 70));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnitemdetails1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnitemdetails1.setText("Daily Wastage Report");
        btnitemdetails1.setBorder(null);
        btnitemdetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnitemdetails1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnitemdetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 50));

        kGradientPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 400, 70));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsupplierdetails1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsupplierdetails1.setText("Daily Invoice Details Report");
        btnsupplierdetails1.setBorder(null);
        btnsupplierdetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupplierdetails1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnsupplierdetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 50));

        kGradientPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 400, 70));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsubloc1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsubloc1.setText("Daily Invoice Item Seles Report");
        btnsubloc1.setToolTipText("");
        btnsubloc1.setBorder(null);
        btnsubloc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubloc1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnsubloc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 50));

        kGradientPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 400, 70));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncategorydetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncategorydetails.setText("Daily GRN Summery Report");
        btncategorydetails.setBorder(null);
        btncategorydetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategorydetailsActionPerformed(evt);
            }
        });
        jPanel6.add(btncategorydetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 50));

        kGradientPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 400, 70));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnItemAlertBin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnItemAlertBin.setText("Daily Invoice Credit Sales");
        btnItemAlertBin.setBorder(null);
        btnItemAlertBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemAlertBinActionPerformed(evt);
            }
        });
        jPanel9.add(btnItemAlertBin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 50));

        kGradientPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 190, 400, 70));

        kGradientPanel3.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel3.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbldepartmentdet.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbldepartmentdet.setText("s");
        kGradientPanel3.add(lbldepartmentdet, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 210, 50));

        lbldepartmentcount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbldepartmentcount.setText("fomd¾;fïka;= .Kk");
        kGradientPanel3.add(lbldepartmentcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, 50));

        kGradientPanel1.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 260, 180));

        kGradientPanel4.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel4.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel6.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel6.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        kGradientPanel4.add(kGradientPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 260, 180));

        kGradientPanel7.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel7.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel8.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel8.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        kGradientPanel7.add(kGradientPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 260, 180));

        kGradientPanel4.add(kGradientPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 540, 260, 180));

        kGradientPanel9.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel9.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel10.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel10.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        kGradientPanel9.add(kGradientPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 260, 180));

        kGradientPanel11.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel11.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel12.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel12.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        kGradientPanel11.add(kGradientPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 260, 180));

        kGradientPanel9.add(kGradientPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 540, 260, 180));

        kGradientPanel4.add(kGradientPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 260, 180));

        lblrack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblrack.setText("jLabel1");
        kGradientPanel4.add(lblrack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 40));

        lblRackcount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRackcount.setText("rdlal .Kk");
        kGradientPanel4.add(lblRackcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 210, 40));

        kGradientPanel1.add(kGradientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 600, 260, 180));

        kGradientPanel5.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel5.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblsupplier.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblsupplier.setText("jLabel3");
        kGradientPanel5.add(lblsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 40));

        lblsupplierscount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblsupplierscount.setText("iemhqïlrejka .Kk");
        kGradientPanel5.add(lblsupplierscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 230, 40));

        kGradientPanel1.add(kGradientPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 260, 180));

        kGradientPanel13.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel13.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel14.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel14.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        kGradientPanel13.add(kGradientPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 260, 180));

        kGradientPanel15.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel15.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel16.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel16.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        kGradientPanel15.add(kGradientPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 260, 180));

        kGradientPanel13.add(kGradientPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 540, 260, 180));

        kGradientPanel17.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel17.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel18.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel18.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        kGradientPanel17.add(kGradientPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 260, 180));

        kGradientPanel19.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel19.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel20.setkEndColor(new java.awt.Color(51, 255, 204));
        kGradientPanel20.setkStartColor(new java.awt.Color(204, 255, 255));
        kGradientPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        kGradientPanel19.add(kGradientPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 260, 180));

        kGradientPanel17.add(kGradientPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 540, 260, 180));

        kGradientPanel13.add(kGradientPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 260, 180));

        lblItem.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblItem.setText("jLabel1");
        kGradientPanel13.add(lblItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 40));

        lblItemCount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblItemCount.setText("NdKav .Kk");
        kGradientPanel13.add(lblItemCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, 40));

        kGradientPanel1.add(kGradientPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 600, 260, 180));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 1460, 10));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Live Update Informations");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 470, 40));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pricechangereportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pricechangereportActionPerformed
       /* DepartmentInformation dj = new DepartmentInformation(null,true);

        dj.setVisible(true);*/
       
       dailyitemchangeviewreport dailyitemchangeviewreport1 = new dailyitemchangeviewreport();
       dailyitemchangeviewreport1.setVisible(true);
       

    }//GEN-LAST:event_btn_pricechangereportActionPerformed

    private void btnrackdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrackdetailsActionPerformed
      DailyInvoiceSummaryReport DailyInvoiceSummaryReport1 = new DailyInvoiceSummaryReport();
      DailyInvoiceSummaryReport1.setVisible(true);
    }//GEN-LAST:event_btnrackdetailsActionPerformed

    private void btnitemdetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnitemdetails1ActionPerformed
      DailyWastageReport DailyWastageReport1 = new DailyWastageReport();
      DailyWastageReport1.setVisible(true);
    }//GEN-LAST:event_btnitemdetails1ActionPerformed

    private void btnsupplierdetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupplierdetails1ActionPerformed
       DailyInvoiceDetailsReport DailyInvoiceDetailsReport1 = new DailyInvoiceDetailsReport();
       DailyInvoiceDetailsReport1.setVisible(true);

    }//GEN-LAST:event_btnsupplierdetails1ActionPerformed

    private void btnsubloc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubloc1ActionPerformed
      DailyInvoiceItemSalesReport DailyInvoiceItemSalesReport1 = new DailyInvoiceItemSalesReport();
      DailyInvoiceItemSalesReport1.setVisible(true);
    }//GEN-LAST:event_btnsubloc1ActionPerformed

    private void btncategorydetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategorydetailsActionPerformed
          DailyGRNsummaryreport DailyGRNsummaryreport1 =new DailyGRNsummaryreport();
          DailyGRNsummaryreport1.setVisible(true);
    }//GEN-LAST:event_btncategorydetailsActionPerformed

    private void btnItemAlertBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemAlertBinActionPerformed
     Daily_Invoice_Credit_Sales Daily_Invoice_Credit_Sales1 = new Daily_Invoice_Credit_Sales();
     Daily_Invoice_Credit_Sales1.setVisible(true);
    }//GEN-LAST:event_btnItemAlertBinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnItemAlertBin;
    private javax.swing.JButton btn_pricechangereport;
    private javax.swing.JButton btncategorydetails;
    private javax.swing.JButton btnitemdetails1;
    private javax.swing.JButton btnrackdetails;
    private javax.swing.JButton btnsubloc1;
    private javax.swing.JButton btnsupplierdetails1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel10;
    private keeptoo.KGradientPanel kGradientPanel11;
    private keeptoo.KGradientPanel kGradientPanel12;
    private keeptoo.KGradientPanel kGradientPanel13;
    private keeptoo.KGradientPanel kGradientPanel14;
    private keeptoo.KGradientPanel kGradientPanel15;
    private keeptoo.KGradientPanel kGradientPanel16;
    private keeptoo.KGradientPanel kGradientPanel17;
    private keeptoo.KGradientPanel kGradientPanel18;
    private keeptoo.KGradientPanel kGradientPanel19;
    private keeptoo.KGradientPanel kGradientPanel20;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private keeptoo.KGradientPanel kGradientPanel7;
    private keeptoo.KGradientPanel kGradientPanel8;
    private keeptoo.KGradientPanel kGradientPanel9;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblItemCount;
    private javax.swing.JLabel lblRackcount;
    private javax.swing.JLabel lbldepartmentcount;
    private javax.swing.JLabel lbldepartmentdet;
    private javax.swing.JLabel lblrack;
    private javax.swing.JLabel lblsupplier;
    private javax.swing.JLabel lblsupplierscount;
    // End of variables declaration//GEN-END:variables
}
