
package view.EntryNotes;

import controller.ManageGoodReceiveNote;
import controller.ManageItem;
import controller.ManagePurchaseOrder;
import controller.ManageStore;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.io.InputStream;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import model.GRN;
import model.PurchaseOrders;
import view.BasicInformation.ItemList;

public class PurchaseOrder extends javax.swing.JDialog {

    PurchaseOrders order = new PurchaseOrders();
    ManagePurchaseOrder manageorder = new ManagePurchaseOrder(order);
    
    Icon arrow = new ImageIcon("arrow.png");
    
    double qty, bprice=0, bTotal=0, total=0;
    
    public PurchaseOrder(java.awt.Frame parent, boolean modal) throws FontFormatException, IOException {
        super(parent, modal);
        initComponents();
        
        table.getTableHeader().setFont(new Font("Nirmala UI", Font.PLAIN, 12));
        generateID();
        date.setDateToToday();   
        getStores();
        
    }
    
    public void getStores(){
        try{
            stores.addItem("-select-");
            ManageStore store =new ManageStore();
            ResultSet rs = store.getStores();
            
            while(rs.next()){
                stores.addItem(rs.getString("location"));
            }
        }catch (Exception ex) {
            System.out.println("line 48" + ex.getMessage());
        }
    }

      public void generateID(){
        try {
            String grn="";
            ResultSet rs = manageorder.displayAll();
            while(rs.next()){
                grn = rs.getString("F23No").toString();
            } 

            if(grn == ""){
                grn = "PRO22KT000001";
            }else{
                int no = Integer.valueOf(grn.substring(8));
                int nno = ++no;
            
                if(String.valueOf(nno).length() == 1){
                    grn = "PRO22KT00000" + String.valueOf(nno);
                }else if(String.valueOf(nno).length() == 2){
                    grn = "PRO22KT0000" + String.valueOf(nno);
                }else if(String.valueOf(nno).length() == 3){
                    grn = "PRO22KT000" + String.valueOf(nno);
                }else if(String.valueOf(nno).length() == 4){
                    grn = "PRO22KT00" + String.valueOf(nno);
                }else if(String.valueOf(nno).length() == 5){
                    grn = "PRO22KT0" + String.valueOf(nno);
                }else{
                    grn = "PRO22KT" + String.valueOf(nno);
                }
            }            
            
            System.out.println(grn);
            F23No.setText(grn);
        } catch (Exception ex) {
            System.out.println("line 55" + ex.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        F23No = new javax.swing.JTextField();
        stores = new javax.swing.JComboBox<>();
        storeID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        supplierName = new javax.swing.JTextField();
        supplierNo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        date = new com.github.lgooddatepicker.components.DatePicker();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        stockQty = new javax.swing.JTextField();
        buyingPrice = new javax.swing.JTextField();
        itemQty = new javax.swing.JTextField();
        buyingTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        subTotal = new javax.swing.JTextField();
        itemName = new javax.swing.JTextField();
        itemNo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 255, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 102, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("භාණ්ඩ ඇනවුම් සටහන F-23A");
        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 19)); // NOI18N
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, 708, -1));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setAutoscrolls(true);

        jLabel2.setText("F-23 අංකය ");
        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 15)); // NOI18N

        F23No.setEditable(false);

        stores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                storesItemStateChanged(evt);
            }
        });
        stores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storesMouseClicked(evt);
            }
        });

        storeID.setEditable(false);
        storeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeIDActionPerformed(evt);
            }
        });

        jLabel4.setText("දිනය");
        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 15)); // NOI18N

        jLabel5.setText(" සැපයුම්කරු ");
        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 15)); // NOI18N

        supplierName.setEditable(false);
        supplierName.setText("F1");
        supplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierNameActionPerformed(evt);
            }
        });
        supplierName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                supplierNameKeyPressed(evt);
            }
        });

        supplierNo.setEditable(false);
        supplierNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                supplierNoKeyPressed(evt);
            }
        });

        jLabel11.setText("ස්ථානය ");
        jLabel11.setFont(new java.awt.Font("Nirmala UI", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(F23No)
                    .addComponent(stores, 0, 145, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storeID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(supplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(F23No, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(stores, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(storeID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplierNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(supplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        kGradientPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 69, 678, -1));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setAutoscrolls(true);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "අනු අංකය ", "විස්තරය ", "පවතින තොගය", "ගැනුම් මිල", "ප්‍රමාණය", "ගැනුම් එකතුව "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        table.setToolTipText("");
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(0).setPreferredWidth(30);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(1).setPreferredWidth(60);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(2).setPreferredWidth(100);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(3).setPreferredWidth(80);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(4).setPreferredWidth(80);
            table.getColumnModel().getColumn(5).setResizable(false);
            table.getColumnModel().getColumn(5).setPreferredWidth(80);
            table.getColumnModel().getColumn(6).setResizable(false);
            table.getColumnModel().getColumn(6).setPreferredWidth(80);
        }

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 657, 174));

        stockQty.setEditable(false);
        jPanel4.add(stockQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 100, 25));

        buyingPrice.setBackground(new java.awt.Color(0, 204, 0));
        buyingPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buyingPriceKeyReleased(evt);
            }
        });
        jPanel4.add(buyingPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 100, 25));

        itemQty.setBackground(new java.awt.Color(255, 255, 0));
        itemQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemQtyKeyReleased(evt);
            }
        });
        jPanel4.add(itemQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 100, 25));

        buyingTotal.setEditable(false);
        buyingTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyingTotalActionPerformed(evt);
            }
        });
        jPanel4.add(buyingTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 99, 25));

        jLabel6.setText("එකතුව  ");
        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 15)); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        subTotal.setEditable(false);
        subTotal.setText("0.00");
        subTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTotalActionPerformed(evt);
            }
        });
        jPanel4.add(subTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 106, 25));

        itemName.setEditable(false);
        itemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameActionPerformed(evt);
            }
        });
        jPanel4.add(itemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 10, 120, 25));

        itemNo.setEditable(false);
        itemNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNoActionPerformed(evt);
            }
        });
        itemNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemNoKeyPressed(evt);
            }
        });
        jPanel4.add(itemNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 83, 25));

        kGradientPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 178, 680, 250));

        jButton1.setText("New");
        jButton1.setAutoscrolls(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 110, -1));

        jButton2.setText("Save");
        jButton2.setAutoscrolls(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 110, -1));

        jButton3.setText("Print");
        jButton3.setAutoscrolls(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 110, -1));

        jButton4.setText("Close");
        jButton4.setAutoscrolls(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 110, -1));

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void supplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierNameActionPerformed

    private void buyingTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyingTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyingTotalActionPerformed

    private void itemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNameActionPerformed

    private void storeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storeIDActionPerformed

    
    supplierSearch search = new supplierSearch(null,true);
    private void supplierNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierNameKeyPressed
        try{
            if (evt.getKeyCode() == KeyEvent.VK_F1) {
         
            search.setVisible(true);
            supplierNo.setText(search.code);
            supplierName.setText(search.name);
            }

        }catch(Exception e)
        {
           System.out.println("line 1322: " +e.getMessage());
        }
    }//GEN-LAST:event_supplierNameKeyPressed

    private void supplierNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplierNoKeyPressed
         try{
            if (evt.getKeyCode() == KeyEvent.VK_F1) {
         
            search.setVisible(true);
            supplierNo.setText(search.code);
            supplierName.setText(search.name);
            }

        }catch(Exception e)
        {
           System.out.println("line 1322: " +e.getMessage());
        }
    }//GEN-LAST:event_supplierNoKeyPressed

    private void storesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storesMouseClicked
       
    }//GEN-LAST:event_storesMouseClicked

    private void storesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_storesItemStateChanged
        try{
            ManageStore store = new ManageStore();
            if (stores.getSelectedIndex() !=0 ) {
                ResultSet rs = store.getStoreID(stores.getSelectedItem().toString());
                System.out.println(stores.getSelectedItem().toString());
                while(rs.next()){
                    storeID.setText(rs.getString("stcode"));
                }
            }

        }catch(Exception e)
        {
           System.out.println("line 1322: " +e.getMessage());
        }
    }//GEN-LAST:event_storesItemStateChanged

    private void itemNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNoActionPerformed

    
    ItemList itemSearch = new ItemList(null, true);
   
    private void itemNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemNoKeyPressed
        try{
            if (evt.getKeyCode() == KeyEvent.VK_F1) {
            
            itemNo.setText("");
            itemName.setText("");
            stockQty.setText("");
            buyingPrice.setText("");
            itemQty.setText("");
            buyingTotal.setText("");

                
            itemSearch.setVisible(true);
            itemNo.setText(itemSearch.No);
            
            int Code = Integer.valueOf(itemSearch.No);
            
            ManageItem items = new ManageItem();
            ResultSet result = items.selectItemdata(Code);
            
            while(result.next()){
                itemNo.setText(String.valueOf(result.getInt("code")));
                itemName.setText(result.getString("itemName"));
//                description = result.getString("itemName");
                buyingPrice.setText(String.valueOf(result.getDouble("costPrice")));
                stockQty.setText(String.valueOf(result.getDouble("stockQty")));
            }
        }

        }catch(Exception e)
        {
           System.out.println("line 1242: " +e.getMessage());
        }
    }//GEN-LAST:event_itemNoKeyPressed

    int rowIndex= -2;
    private void itemQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemQtyKeyReleased
       addItemsToTable(evt);
    }//GEN-LAST:event_itemQtyKeyReleased

    public void addItemsToTable(java.awt.event.KeyEvent evt){
         try{
            if (evt.getKeyCode() != KeyEvent.VK_ENTER) {
                
                qty = Double.valueOf(itemQty.getText());
                bprice = Double.valueOf(buyingPrice.getText());
                bTotal = qty * bprice;
                buyingTotal.setText(String.valueOf(bTotal));
                total = Double.valueOf(subTotal.getText()) + bTotal;
                ManageItem item = new ManageItem();
                ResultSet rs = item.getItemStock(Integer.valueOf(itemNo.getText().toString()));
                while(rs.next()){
                    double mqty = rs.getDouble("maxQty");
                    double sqty = rs.getDouble("stockQty");
                    
                    if((sqty+qty)> mqty){
                        JOptionPane.showMessageDialog(null, "The amount of item " +itemNo.getText() + " quantity you orderd exceed it's max quantity of"+ mqty +".", "SuperMarket Management", JOptionPane.ERROR_MESSAGE);
                        itemQty.setText("0.00");
                    }
                }
            }else{
                if(itemQty.getText().length() != 0){
                    if(Double.valueOf(itemQty.getText()) > Double.valueOf(stockQty.getText())){
                        JOptionPane.showMessageDialog(null, "No enough item aqantity available stock", "SuperMarket Management", JOptionPane.ERROR_MESSAGE);
                    }else{
                        TableModel tm = table.getModel();
                        if(tm.getRowCount() > 0){
                            tm.setValueAt("", 0, 0);
                            tm.setValueAt("", rowIndex, 0);
                        } else{               
                            rowIndex = 0;
                        }

                        DefaultTableModel model = (DefaultTableModel) table.getModel();
                        Vector vec = new Vector();
                        vec.add(">");
                        vec.add(itemNo.getText().toString());
                        vec.add(itemName.getText().toString());
                        vec.add(stockQty.getText().toString());
                        vec.add(buyingPrice.getText().toString());
                        vec.add(itemQty.getText().toString());
                        vec.add(buyingTotal.getText().toString());


                        subTotal.setText(String.valueOf(total));

                        model.insertRow(0, vec);
                        table.setModel(model);

                        itemNo.setText("");
                        itemName.setText("");
                        stockQty.setText("");
                        buyingPrice.setText("");
                        itemQty.setText("");
                        buyingTotal.setText("");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Please enter the item quantity" + order.getcode(), "SuperMarket Management", JOptionPane.ERROR_MESSAGE);
                }
            }

        }catch(Exception e)
        {
           System.out.println("line 1242: " +e.getMessage());
        }
    }
    private void subTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subTotalActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        try{
            TableModel tm = table.getModel();
             
            if((rowIndex != -2) && (table.getSelectedRow() != rowIndex)){
                tm.setValueAt("", 0, 0);
                tm.setValueAt("", rowIndex, 0);
                rowIndex =  table.getSelectedRow();
                tm.setValueAt(">", rowIndex, 0);
                
            }else if(table.getSelectedRow() == rowIndex){
                rowIndex =  table.getSelectedRow();
                tm.setValueAt("*", rowIndex, 0);
                
            }else{
                tm.setValueAt("", 0, 0);
                rowIndex =  table.getSelectedRow();
                tm.setValueAt(">", rowIndex, 0);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        } 
    }//GEN-LAST:event_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try{
           if(F23No.getText().length() ==0){
               JOptionPane.showMessageDialog(rootPane, "Invalid Purchase Order ID! Please Check again","SuperMarket Management" , JOptionPane.ERROR_MESSAGE);
            }else if(date.getDate().equals(null)){
                JOptionPane.showMessageDialog(rootPane, "Please enter the date","SuperMarket Management" , JOptionPane.ERROR_MESSAGE);
            }else if((storeID.getText().length() == 0 ) && (stores.getSelectedIndex() == 0)){
                JOptionPane.showMessageDialog(rootPane, "Please enter the store details","SuperMarket Management" , JOptionPane.ERROR_MESSAGE);
            }else if((supplierNo.getText().length() == 0 ) && (supplierName.getText().length() == 0)){
                JOptionPane.showMessageDialog(rootPane, "Please enter the supplier details","SuperMarket Management" , JOptionPane.ERROR_MESSAGE);
            }else if(table.getRowCount()==0){
                JOptionPane.showMessageDialog(rootPane, "There are no items to save in your GRN","SuperMarket Management" , JOptionPane.ERROR_MESSAGE);
            }else{
                order.order(F23No.getText().toString(),java.sql.Date.valueOf(date.getDate())); 
                int i = manageorder.saveOrder();

                if(i==1){
                    order.setPurchaseOrderRecords(storeID.getText().toString(), Double.valueOf(subTotal.getText()), Integer.valueOf(supplierNo.getText()));
                    int j = manageorder.saveOrderRecords();

                    if(j==1){
                        DefaultTableModel dtm= (DefaultTableModel)table.getModel();
                        int RowCount1= table.getRowCount();
                            System.out.println(RowCount1);

                        int r2 =0;
                        for(int n=0; n< RowCount1; n++){
                            System.out.println(dtm.getValueAt(j, 0).toString());
                            System.out.println(dtm.getValueAt(j, 1).toString());
                            System.out.println(dtm.getValueAt(j, 2).toString());
                            System.out.println(dtm.getValueAt(j, 3).toString());
                            System.out.println(dtm.getValueAt(j, 4).toString());

                            order.setpurchaseorderitems(Integer.valueOf(dtm.getValueAt(n,1).toString()), Double.valueOf(dtm.getValueAt(n,5).toString()), Double.valueOf(dtm.getValueAt(n,4).toString()), Double.valueOf(dtm.getValueAt(n,6).toString()));
                            int k = manageorder.saveOrderItems();
                            if(k ==1){
                                r2++;
                            }
                        }
                        if(r2 == RowCount1){
                            clearAll();
                                JOptionPane.showMessageDialog(null, "orders saved succesfully" ,"SuperMarket Management", JOptionPane.INFORMATION_MESSAGE);
                        }else{
                            JOptionPane.showMessageDialog(null, "Error in saving order items  ", "SuperMarket Management", JOptionPane.ERROR_MESSAGE);
                        } 
                        
                    }else{
                        JOptionPane.showMessageDialog(null, "Error in saving order records" ,"SuperMarket Management", JOptionPane.INFORMATION_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Error in saving orders" ,"SuperMarket Management", JOptionPane.INFORMATION_MESSAGE);
                }
            }
       }catch(Exception e){
            System.out.println(e.getMessage());
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    public void clearAll(){
        try{
            generateID();
            date.setDateToToday();
            stores.setSelectedIndex(0);
            storeID.setText("");
            supplierName.setText("");
            supplierNo.setText("");
            subTotal.setText("");
            total =0;
            DefaultTableModel newt = (DefaultTableModel)table.getModel();
            newt.setRowCount(0);
        }catch(Exception e){
            System.out.println(e.getMessage());
        } 
        

    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clearAll();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buyingPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buyingPriceKeyReleased
//        Double qty = Double.valueOf(itemQty.getText());
//        Double price = Double.valueOf(buyingPrice.getText());
//        Double total = qty * price;
//        buyingTotal.setText(String.valueOf(total));
        addItemsToTable(evt);
    }//GEN-LAST:event_buyingPriceKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    PurchaseOrder dialog = new PurchaseOrder(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (FontFormatException ex) {
                    Logger.getLogger(PurchaseOrder.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(PurchaseOrder.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField F23No;
    private javax.swing.JTextField buyingPrice;
    private javax.swing.JTextField buyingTotal;
    private com.github.lgooddatepicker.components.DatePicker date;
    private javax.swing.JTextField itemName;
    private javax.swing.JTextField itemNo;
    private javax.swing.JTextField itemQty;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField stockQty;
    private javax.swing.JTextField storeID;
    private javax.swing.JComboBox<String> stores;
    private javax.swing.JTextField subTotal;
    private javax.swing.JTextField supplierName;
    private javax.swing.JTextField supplierNo;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
